= Asciidoctor 简明教程
杨波 <bo.yang@telecwin.com>
:icons: font
:stem:
:toc:
:sectnums:

Asciidoctor 是一个比 Markdown 更先进、复杂的文档书写和生成工具，它定义了类似 Markdown 的文字格式，但是能生成更好看的文档、提供
了更强大的排版和文档创作功能，尤其是能非常方便地在文档中加入示例代码和注释。

下面让我们开始Asciidoctor使用之旅吧...

== 首先是工具

[quote, 《论语·卫灵公》, idea+asciidoctor插件就不错]
____
工欲善其事，必先利其器
____

== Asciidoctor 文档的主体结构

Asciidoctor 分 header 和 序(preamble)、节(section)、块(block)、段落 等部分。
在 header 中可以定义一些属性，这些属性就像是开关，告诉 Asciidoctor 打开哪些功能。

比如本文的 header 是这样的

    = Asciidoc 简明教程
    杨波 <bo.yang@telecwin.com>
    :icons: font <1>
    :stem: <2>
    :toc: <3>
    :sectnums: <4>

<1> 告诉 Asciidoctor 使用font-awesome来显示警告图示，没有这个开关，警告块只会显示WARN字样，很难看。
<2> 告诉 Asciidoctor 支持在文档中加入 https://asciidoctor.org/docs/user-manual/#mathematical-expressions[数学公式]。
<3> 告诉 Asciidoctor 生成目录
<4> 告诉 Asciidoctor 给小节Section添加数字

== 各种格式示例

=== 阅读方法

我们将边做边写，对每一个功能都是先给出示例，紧接着是如何做，最后再详细讲解这个功能。

=== 段落

====
这是一个段落，这是一个段落，这是一个段落，这是一个段落，这是一个段落，这是一个段落，这是一个段落

这是另外一个段落，这是另外一个段落，这是另外一个段落，这是另外一个段落，这是另外一个段落，这是另外一个段落
====

这样写就可以了，段落之间留一空行

....
这是一个段落，这是一个段落，这是一个段落，这是一个段落，这是一个段落，这是一个段落，这是一个段落

这是另外一个段落，这是另外一个段落，这是另外一个段落，这是另外一个段落，这是另外一个段落，这是另外一个段落
....

=== 换行显示而不是另起一个分段落

====
敲了回车换行键就换行显示！ +
不是很好吗？
====

是这样达成的

    换行就换行！ +
    不是很好吗？

CAUTION: **+**加号前面要有一个空格，否则不起作用。

=== 数学公式

****
stem:[sqrt(4)=2]
****

这样写的

    stem:[sqrt(4)=2]

=== 各种警告、提示 (admonitions)

====
NOTE: 这是有用信息。

TIP: 小技巧

IMPORTANT: 重要事情说三遍。

CAUTION: 注意了，数学公式用的 MathJS、FontAwesome 用的 CSS 在中国很可能访问很慢或者访问不了，需要将这些 js、css 都本地化。

WARNING: 这是一个警告。
====

这样写的

    NOTE: 这是有用信息。

    TIP: 小技巧

    IMPORTANT: 重要事情说三遍。

    CAUTION: 注意了，数学公式用的 MathJS、FontAwesome 用的 CSS 在中国很可能访问很慢或者访问不了，需要将这些 js、css 都本地化。

    WARNING: 这是一个警告。

重要程度从轻到重。

=== 代码片段

====
[source, groovy]
class HelloGroovy {
    def name
    def sayHello(){
        println("hello!")
    }
}
====

看起来还不错！是这样写的

    [source, groovy]
    class HelloGroovy {
        def name
        def sayHello(){
            println("hello!")
        }
    }

=== 加注解的代码片段

====
[source, groovy]
class HelloGroovy {
    def name <1>
    def sayHello(){ <2>
        println("hello!")
    }
}

<1> 定义属性
<2> 定义方法
====

是这样写的
[literal, subs="-callouts"]
....
[source, groovy]
class HelloGroovy {
    def name <1>
    def sayHello(){ <2>
        println("hello!")
    }
}

<1> 定义属性
<2> 定义方法
....

=== 块
==== 示例块(example block)

====
这是一个示例块，是不是很醒目？
====

是这样写的

    ====
    这是一个示例块，是不是很醒目？
    ====

==== 去掉注释(callouts)的原文块(literal block)

[example]
--
[literal, subs="-callouts"]
....
[source, groovy]
class HelloGroovy {
    def name <1>
    def sayHello(){ <2>
        println("hello!")
    }
}

<1> 定义属性
<2> 定义方法
....
--

是这样写的

[literal, subs="-callouts"]
......
[literal, subs="-callouts"]
....
[source, groovy]
class HelloGroovy {
    def name <1>
    def sayHello(){ <2>
        println("hello!")
    }
}

<1> 定义属性
<2> 定义方法
....
......

NOTE: 这里需要用两个 "...." 将“原文块”包裹起来，并且添加了替换参数 subs="-callouts"，以便<1>不显示成注释数字。

==== 表格

[example]
--
[%header]
|===
| 表头1 | 表头2
| 单元格11 | 单元格12
| 单元格21 | 单元格22
| 单元格31 | 单元格32
|===
--

是这样写的

[literal]
--
[%header]
|===
| 表头1 | 表头2
| 单元格11 | 单元格12
| 单元格21 | 单元格22
| 单元格31 | 单元格32
|===
--

==== 参考手册

* https://asciidoctor.org/docs/user-manual/#built-in-blocks-summary[各种块的定义方法，以及块如何处理其中的字符]
* https://asciidoctor.org/docs/user-manual/#applying-substitutions[指定替换模式]

== 在gradle项目中集成 asciidoctor

=== 添加依赖

**build.gradle**
[source, groovy]
--
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.9.2'
    }
}

plugins {
    id 'groovy'
    id 'java'
}
apply plugin: 'org.asciidoctor.convert'
--

=== 配置文档的路径
**build.gradle**
[source, groovy]
--
asciidoctor {
    sourceDir = file('docs')
}
--

=== 执行文档构建任务

    gradlew.bat asciidoctor

就会在 build/asciidoc/html5 目录下看到生成的文档了。

== 参考资料

1. 阅读 https://asciidoctor.org/#c-windows[安装文档]。
2. https://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Asciidoctor的Gradle插件] 可以用来生成Asciidoctor项目文档。
